### ISSUE TITLE
irrelevant pip-install warning

### ISSUE THREAD

**Issue by brobr** [htseq/htseq#1]
https://github.com/pypa/setuptools/issues/2066

**Comment by iosonofabio** [comment]
Thank you. This is an upstream issue as you have identified already.

**Comment by brobr** [comment]
Hi have a look at the above setuptools issue again; they answered and remarked that the program (HTSSeq) is calling `cython` where `cython3` might be appropriate..

**Comment by iosonofabio** [comment]
cython is a symbolic link to cython3 on many platforms. Moreover, python2 is beyond its life span and HTSeq will drop it entirely from the next release. So I think you'd better upgrade to python/cython 3 and stop using python2 to avoid these issues from now on.

Cheers,
