### ISSUE TITLE
Exception type: TypeError, raised in random.py:262

### ISSUE THREAD

**Issue by anderdnavarro** [htseq/htseq#10]
Hi,

I was trying to run htseq-count with the following configuration but I always have the same error:

`htseq-count --order=pos --max-reads-in-buffer=100000000 --nonunique=random 01.mdups.Aligned.sortedByCoord.out.bam gencode.v33.annotation.gtf.gz

100000 GFF lines processed.
200000 GFF lines processed.
300000 GFF lines processed.
400000 GFF lines processed.
500000 GFF lines processed.
600000 GFF lines processed.
700000 GFF lines processed.
800000 GFF lines processed.
900000 GFF lines processed.
1000000 GFF lines processed.
1100000 GFF lines processed.
1200000 GFF lines processed.
1300000 GFF lines processed.
1400000 GFF lines processed.
1500000 GFF lines processed.
1600000 GFF lines processed.
1700000 GFF lines processed.
1800000 GFF lines processed.
1900000 GFF lines processed.
2000000 GFF lines processed.
2100000 GFF lines processed.
2200000 GFF lines processed.
2300000 GFF lines processed.
2400000 GFF lines processed.
2500000 GFF lines processed.
2600000 GFF lines processed.
2700000 GFF lines processed.
2800000 GFF lines processed.
2900000 GFF lines processed.
2909532 GFF lines processed.

Error occured when processing input (record #57 in file 01.mdups.Aligned.sortedByCoord.out.bam):
  'set' object is not subscriptable
  [Exception type: TypeError, raised in random.py:262]`

If I change `--nonunique random` by `--nonunique fraction` it works fine.

-- SOLUTION --
I was reading the script that calls the function "random" (`HTSeq/scripts/count.py`) and I think I've fixed the error because now it doesn't break. In line 285, I've changed:
- `fsi = random.choice(fs)` ➜ `fsi = random.choice(list(fs))`

I hope this may help you.

Versions:
- python 3.7.3
- htseq-count 0.12.4

**Comment by iosonofabio** [comment]
Thank you, this looks easy so I'll try to fix it in the next days
