### ISSUE TITLE
raw_optional_fields tag type "j" is invalid. Do you mean "f"?

### ISSUE THREAD

**Issue by cytham** [htseq/htseq#11]
I am encountering error parsing the sam file after generating it with get_sam_line().

When I view it with samtools, I get the following error:
[E::sam_parse1] unrecognized type j
[W::sam_read1] Parse error at line 457
[main_samview] truncated file.

This is caused by your labeling of "j" to a float value of an optional field tag. And I found the code in your _HTSeq.pyx script at line 1565 as shown below.

```    
    def raw_optional_fields(self):
        res = []
        for op in self.optional_fields:
            if op[1].__class__ == str:
                if len(op[1]) == 1:
                    tc = "A"
                else:
                    tc = "Z"
            elif op[1].__class__ == int:
                tc = "i"
            elif op[1].__class__ == float:
                tc = "j"
            else:
                tc = "H"
            res.append(":".join([op[0], tc, str(op[1])]))
        return res
```

Type "j" is not recognized by samtools or pysam and I don't know why you use it. Please change it to "f" (real number) or refer to https://samtools.github.io/hts-specs/SAMtags.pdf.

Thanks

**Comment by iosonofabio** [comment]
Thank you. Legit bug. Fixed in 797f802 to "f". Tests are running now.
