### ISSUE TITLE
installation not working

### ISSUE THREAD

**Issue by kOoLiNuS** [htseq/htseq#12]
Hello!
On our Ubuntu server {up-2-date Ubuntu 16.04.6 LTS on a 64bit CPU} after following the

`pip install matplotlib`
`pip install Cython`
`pip install pysam`
`pip install HTSeq`

routine, lauchin the `htseq-count` command here's the result I have

> htseq-count -h
> Traceback (most recent call last):
>   File "/usr/local/bin/htseq-count", line 3, in <module>
>     import HTSeq.scripts.count
>   File "/usr/local/lib/python3.5/dist-packages/HTSeq/__init__.py", line 13, in <module>
>     from HTSeq._HTSeq import *
>   File "__init__.pxd", line 918, in init HTSeq._HTSeq
> ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
> root@magilla:~# htseq-count -
> Traceback (most recent call last):
>   File "/usr/local/bin/htseq-count", line 3, in <module>
>     import HTSeq.scripts.count
>   File "/usr/local/lib/python3.5/dist-packages/HTSeq/__init__.py", line 13, in <module>
>     from HTSeq._HTSeq import *
>   File "__init__.pxd", line 918, in init HTSeq._HTSeq
> ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject

Thanks in advance, 
Nicola

**Comment by iosonofabio** [comment]
I'll look into it. That installation is more than 4 years old so I'm not sure whether bumpy has changed their ABI since

**Comment by iosonofabio** [comment]
I recently revamped the CI instructions and HTSeq installs happily on the latest ubuntu. I'm therefore closing this now, if you are still experiencing this issue please specify the versions of your packages:

- numpy
- matplotlib
- Cython
- pysam
- HTSlib
- samtools
- HTSeq

and we can go from there.
