### ISSUE TITLE
  <built-in function delete__Pair_int_obj> returned a result with an error set

### ISSUE THREAD

**Issue by cellmem** [htseq/htseq#19]
I'm getting this error message when running the htseq-count script:

  <built-in function delete__Pair_int_obj> returned a result with an error set
  [Exception type: SystemError, raised in _HTSeq_internal.py:33]

Any thoughts would be appreciated.

I'm working on a cluster environment with a local install of HTseq and  python anaconda 3.7

**Comment by iosonofabio** [comment]
Hi,

Please provide the full command line call, operating system, full stack trace

**Comment by iosonofabio** [comment]
This has been open for a while but no input from her. Closing now, can be reopened if the user supplies necessary info.

**Comment by TypicalSEE** [comment]
Hi, I got the same error. Here's the command line:
```
htseq-count -s no -f bam -r pos -i Parent CH.bam Gnetum_montanum.gff
```
Appreciate it very much if you could help me!

**Comment by iosonofabio** [comment]
Thanks for reporting

**Comment by iosonofabio** [comment]
Ping, please attach small example files or I'll close for inactivity :smirk:
