### ISSUE TITLE
OverflowError, raised in _HTSeq.pyx:1163

### ISSUE THREAD

**Issue by Tao2020yes** [htseq/htseq#2]
Hi, I am running htseq-count [htseq-count -r name -a 30 -t gene -i ID $in.sam $gff3 > $outcount], but with some, not all sam files, htseq gave errors and terminated the progress. The errors are always the same (as attached), except the line numbers are different. Can you suggest how to handle this and get the gene count table? Thanks.

![image](https://user-images.githubusercontent.com/59539873/79697830-fc4c2800-8252-11ea-887b-76432cf68ee8.png)
<img width="776" alt="Screen Shot 2020-04-19 at 3 32 55 PM" src="https://user-images.githubusercontent.com/59539873/79697852-1980f680-8253-11ea-88b4-5c92a7c202e4.png">

**Comment by iosonofabio** [comment]
Please provide the SAM/BAM and GFF files in question (a goodle drive link would work), the version of HTSeq you are using, and whteher you are using python2 or 3.

Thanks
Fabio

**Comment by Tao2020yes** [comment]
Thank you for your prompt response, Fabio. 

Here is the link (https://drive.google.com/drive/folders/1ll_gdQRYYq-95WEoozHzVVF2Ykoj-69h?usp=sharing) to download compressed gff3 and SAM that gave me that error. Please let me know if you have any issues accessing it.

Below are the packages I applied to this data analysis.
module load gcc/6.2.0 gmap-gsnap/2018.02.12 
module load gcc/6.2.0 samtools/1.3.1 
module load gcc/6.2.0  python/2.7.12 htseq/0.9.1

Best,
Tao

**Comment by iosonofabio** [comment]
Thank you.

How without saying, upgrade to the latest htseq first

**Comment by iosonofabio** [comment]
Closing as it referred to an ancient version of HTSeq and the user didn't respond to upgrade prods.
