### ISSUE TITLE
Build question.

### ISSUE THREAD

**Issue by BJWiley233** [htseq/htseq#21]
Hi,

Since I am building without root access I installed using setuptools.  After I run `python3 setup.py build install --prefix=$TOOLS` the package gets installed to my site-packages correctly but after starting python I get error because it tries to import from the source github clone directory.  I have to delete the github clone folder for it to run.  Has anyone else tried building locally like this and get same "issue"?  This is response because it's reading from build HTSeq folder in clone directory but the HTSeq._HTSeq.py is under the egg where I installed it.
```
File "/export/home/bwiley4/tools/htseq/HTSeq/__init__.py", line 13, in <module>
    from HTSeq._HTSeq import *
ModuleNotFoundError: No module named 'HTSeq._HTSeq'
```

**Comment by iosonofabio** [comment]
Merry Xmas! That's how Python imports work, please read up on absolute versus relative imports. Closing.

**Comment by BJWiley233** [comment]
Right but I wasn't running from the cloned build directory, I ran from some other directory and it still defaulted to the build which I don't know why cause it wasn't in my PYTHONPATH.

**Comment by iosonofabio** [comment]
Alright, please provide a proper description of what `TOOLS` is, a list of commands from git clone to the one that triggers the error, and a full stacktrace. I'll be happy to take a look: ATM I'm not sure what you are doing.

**Comment by BJWiley233** [comment]
Weird that seems to be able to import now after building from git clone.  Maybe I never cd out of build directory like I thought.   I ran a test with binary `htseq-count` and now I am getting error that seems to be related to Cython even though I have it installed before building and install `htseq`.

```
 <built-in function delete__Pair_int_obj> returned a result with an error set
  [Exception type: SystemError, raised in _HTSeq_internal.py:33]
```

I only get this if I build from this new repo for version 0.13.0.  However when I clone and build from ` simon-anders / htseq` version `0.11.5` the binary works perfectly fine!   So that is pretty weird.

**Comment by iosonofabio** [comment]
Great you solved the original problem.

This is an unrelated problem. Just because you don't get an error message does not mean the software works as expected, as old versions tend to have silent bugs. Open another issue with the complete count, input file, stacktrace, etc. if you need help with that.
