### ISSUE TITLE
Cannot process paired-end alignment found with 'unknown' 'pe_which' status

### ISSUE THREAD

**Issue by kscott94** [htseq/htseq#26]
[kscott94]$ python3 -m HTSeq.scripts.count -f bam -r pos ../../final_bams/file.bam annotation.gtf

Error occured when processing SAM input (record #0 in file ../../final_bams/TS559exoS_totalRNA_March2016_rmdup.bam):
  Cannot process paired-end alignment found with 'unknown' 'pe_which' status.
  [Exception type: ValueError, raised in __init__.py:767]

I don't know what this error means. Here is the head of my file. 

samtools view -h ../../final_bams/TS559exoS_totalRNA_Oct2020_rmdup.sam | head -13
@HD	VN:1.0	SO:coordinate
@SQ	SN:TS559_Genomic_Sequence.seq	LN:2087105
@PG	PN:BS Seeker 2	ID:1	CL:/projects/kscott94@colostate.edu/tools/BSseeker2/bs_seeker2-align.py -i /scratch/summit/kscott94@colostate.edu/bs7/TS559/rep3/TS559exoS_totalRNA_Oct2020_R1_CA_filtered.fastq -g /projects/kscott94@colostate.edu/genome/TS559_genome.fa --temp_dir=/scratch/summit/kscott94@colostate.edu/tmp -m 2 --XS=0.03,3 --bt2--mm --bt-p 10 --aligner=bowtie2 -p /projects/kscott94@colostate.edu/tools/bowtie2/
@PG	PN:BS Seeker 2	ID:1-3297022D	CL:/projects/kscott94@colostate.edu/tools/BSseeker2/bs_seeker2-align.py -i /scratch/summit/kscott94@colostate.edu/bs7/TS559/rep3/TS559exoS_totalRNA_Oct2020_R2_C_filtered.fastq -g /projects/kscott94@colostate.edu/genome/TS559_genome.fa --temp_dir=/scratch/summit/kscott94@colostate.edu/tmp -m 2 --XS=0.03,3 --bt2--mm --bt-p 12 --aligner=bowtie2 -p /projects/kscott94@colostate.edu/tools/bowtie2/
@PG	ID:samtools	PN:samtools	PP:1-3297022D	VN:1.12	CL:samtools merge TS559exoS_totalRNA_Oct2020_filtered_unsorted.bam TS559exoS_totalRNA_Oct2020_R1_CA_filtered.fastq_bsse.bam TS559exoS_totalRNA_Oct2020_R2_C_filtered.fastq_bsse.bam
@PG	ID:samtools.1	PN:samtools	PP:samtools	VN:1.12	CL:samtools view -h -b -q 20 TS559exoS_totalRNA_Oct2020_filtered_unsorted.bam
@PG	ID:samtools.2	PN:samtools	PP:samtools.1	VN:1.12	CL:samtools sort -n -o TS559exoS_totalRNA_Oct2020_mapq_nsorted.bam
@PG	ID:samtools.3	PN:samtools	PP:samtools.2	VN:1.12	CL:samtools fixmate -rm TS559exoS_totalRNA_Oct2020_mapq_nsorted.bam TS559exoS_totalRNA_Oct2020_fixmate.bam
@PG	ID:samtools.4	PN:samtools	PP:samtools.3	VN:1.12	CL:samtools sort TS559exoS_totalRNA_Oct2020_fixmate.bam
@PG	ID:samtools.5	PN:samtools	PP:samtools.4	VN:1.12	CL:samtools markdup -r TS559exoS_totalRNA_Oct2020_fixmate_csorted.bam TS559exoS_totalRNA_Oct2020_rmdup.bam
@PG	ID:samtools.6	PN:samtools	PP:samtools.5	VN:1.12	CL:samtools view -h ../../final_bams/TS559exoS_totalRNA_Oct2020_rmdup.bam
@PG	ID:samtools.7	PN:samtools	PP:samtools.6	VN:1.12	CL:samtools view -h ../../final_bams/TS559exoS_totalRNA_Oct2020_rmdup.sam
A00336:A00336:HT232DRXX:1:2111:6063:35603	1	TS559_Genomic_Sequence.seq	1	255	76S74M	=	1	0	ATATAATTGAGGATGGAAAGTTTGTTATAAGAATTTTTAAGAAGGAAAATGGTGAGTTTAAGATTGAGTATGAAAGATGATTTTTGATATTGATTATATAATTGAGGATGGAAAGTTTGTTATAAGAATTTTTAAGAAGGAAAATGGTGA	*	XO:Z:+FW	XS:i:0	NM:i:0	XM:Z:-----zz-x--z-y---z--z----yx------------zy---z-----------z-----------x--x--	XG:Z:NN_ATGATCCTCGACACTGACTACATAACCGAGGATGGAAAGCCTGTCATAAGAATTTTCAAGAAGGAAAACGGCGA_GT	MQ:i:255	MC:Z:42S92M16S	ms:i:255

**Comment by iosonofabio** [comment]
Thanks for reporting @kscott94 and sorry for the late reply, I have been quite busy.

Could you please share a small BAM file (less than 1M reads) and related GTF file so I can run the test on my machine?

**Comment by iosonofabio** [comment]
@kscott94 any updates on this? Otherwise I'll close for lack of info.
