### ISSUE TITLE
htseq-count error, Could not retrieve index file

### ISSUE THREAD

**Issue by sluxlerch** [htseq/htseq#28]
Hello, 

I am attempting to use the htseq-count tool to generate a count file from a name sorted alignment file generated from paired end data using the following code:

>` htseq-count --format bam --order name -a 0 -q -m intersection-strict --supplementary-alignments ignore --secondary-alignments ignore --stranded no SS0200_S58_vs_iso.mmetsp_shuff.bam $gtfFile > $outdir"S58_iso.mmetsp.HTSeqCounts.tab"`

When I run this script I get the following error though:

> Could not retrieve index file for 'SS0200_S58_vs_iso.mmetsp_shuff.bam'

Since you cannot generate an index file for name sorted bam file, I'm not sure how to resolve the error. I have also run this same script previously with Htseq v0.9.1 and didn't have any problems.

Any help would be appreciated, thanks. 

Software versions: Htseq0.13.5, Python v3.6.8, Samtools v1.9

**Comment by iosonofabio** [comment]
Thanks for reporting, could you please share a small BAM file and a small GTF file that reproduce this issue?

**Comment by sluxlerch** [comment]
Hi Fabio,

Linked here
<https://drive.google.com/drive/folders/1mPMh54HJIMG7LHV72w2dGWmcwjKl4j8h?usp=sharing>
is a google drive folder with a smaller bam and gtf file which will
reproduce the error. I've also included the script used to generate the
name sorted bam file and the htseq script I tested.

Please let me know if there's anything else useful I can provide.

Thank you,

Sarah

On Thu, Oct 7, 2021 at 10:15 PM Fabio Zanini ***@***.***>
wrote:

> Thanks for reporting, could you please share a small BAM file and a small
> GTF file that reproduce this issue?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_htseq_htseq_issues_28-23issuecomment-2D938283835&d=DwMCaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=Xm8qbVzgHOkE2JKYMSS03w&m=dwrclvIft7ttmZLD0pxwk5rOo4c0no4C62nZkApn0No&s=tYX8uFpWMAMsbEowP93rnMVP9lhM_RhQkGt39iqZwu8&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQCYBKHGG3L2S33KHBQERRDUFZH27ANCNFSM5FJZIP3A&d=DwMCaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=Xm8qbVzgHOkE2JKYMSS03w&m=dwrclvIft7ttmZLD0pxwk5rOo4c0no4C62nZkApn0No&s=yLJlu7me-QeFr6Nhqb7kd7FtNmyo9GzUCU_zNHbLF_g&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=Xm8qbVzgHOkE2JKYMSS03w&m=dwrclvIft7ttmZLD0pxwk5rOo4c0no4C62nZkApn0No&s=yo42VXO7avaBMVNdLVBuUM3YGFHfHtvWFn7uylzR_HA&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=dWz0sRZOjEnYSN4E4J0dug&r=Xm8qbVzgHOkE2JKYMSS03w&m=dwrclvIft7ttmZLD0pxwk5rOo4c0no4C62nZkApn0No&s=YNYzBZHbPONlBLpTOasLIfWEEl1XRUZIMo59n5UWV-A&e=>.
>
>


-- 
Dr. Sarah Lerch (she, her, hers)
Postdoctoral Scholar, University of Rhode Island
Kingston, RI

**Comment by iosonofabio** [comment]
I downloaded the `BAM` and `gtf2` files, renamed the `.gtf2` file as `.gtf`, and ran the following command:

```
htseq-count --format bam --order name -a 0 -q -m intersection-strict --supplementary-alignments ignore --secondary-alignments ignore --stranded no test_vs_iso.mmetsp.bam gtf_test.gtf > "output.tab"
```

I debugged a little and it seems like your input BAM file is truncated, because `pysam` cannot open it:

```
OSError: no BGZF EOF marker; file may be truncated
```

Please try the following two things:
1. reupload and **make sure** your example files are not truncated (run the command and make sure you do not get this error).
2. install `HTSeq` from the master Github branch and try again.

A few other things:
- `--order name` is the default already
- `-q` is not a good idea when debugging
- `--format BAM` is deprecated, `pysam` detects the format automatically (and in this case detected a corrupted BAM)

Keep me posted on how those two tasks are going and when you're done with both I'll try again.

**Comment by iosonofabio** [comment]
Thanks, I'll try again but my time is limited. Running this example works on a laptop or virtual machine, so you don't need a supercomputer for that, and the more you do the quicker this can get solved ..

**Comment by sluxlerch** [comment]
I was able to install HTseq from the master branch on my personal laptop and am still running into the same error.

My system and environment settings:

- Ubuntu 18.04.6
- Python 3.9.4
- HTSeq 0.13.5 (installed from cloned master branch)

The script I ran (using shared test files):
`htseq-count -a 0 -m intersection-strict --supplementary-alignments ignore --secondary-alignments ignore --stranded no test_vs_iso.mmetsp.bam gtf_test.gtf > test.tab`

The full error output:

> [E::idx_find_and_load] Could not retrieve index file for 'test_vs_iso.mmetsp.bam'
> 9999 GFF lines processed.
> [E::idx_find_and_load] Could not retrieve index file for 'test_vs_iso.mmetsp.bam'
> Error occured when processing input (record #42 in file test_vs_iso.mmetsp.bam):
>   'utf-8' codec can't decode byte 0xe9 in position 96: invalid continuation byte
>   [Exception type: UnicodeDecodeError, raised in libcutils.pyx:159]
