### ISSUE TITLE
htseq-count error '_StepVector_Iterator_obj' object has no attribute 'next'   [Exception type: AttributeError, raised in StepVector.py:409]

### ISSUE THREAD

**Issue by shijianasdf** [htseq/htseq#30]
After input htseq-count command like this 
> ```r
>htseq-count -f bam -r pos -s yes -m intersection-nonempty /Users/shijian/mydata/bulkRNA/3.bam/P106/P106Aligned.sortedByCoord.out.bam /Users/shijian/mydata/bulkRNA/0.reference/gencode.v38.chr_patch_hapl_scaff.annotation.gtf > /Users/shijian/mydata/bulkRNA/4.counts/P106.txt
> ```

I got error as follow:
> ```r
>'_StepVector_Iterator_obj' object has no attribute 'next'
>  [Exception type: AttributeError, raised in StepVector.py:409]
> ```
my sorted bam file was produced from STAR and indexed with samtools. and I had no idea with this

**Comment by iosonofabio** [comment]
I found what this was, and it's already been fixed in 1.99 during the revamping of the entire Cython interface. Closing.
