### ISSUE TITLE
PySam error

### ISSUE THREAD

**Issue by LegebekeJe** [htseq/htseq#32]
Hi, can someone help me out? I used HTSeq in the past successfully. However, recently I moved my scripts/tools over to a new computing facility and now I keep getting the following issue:

100000 GFF lines processed.
200000 GFF lines processed.
300000 GFF lines processed.
400000 GFF lines processed.
500000 GFF lines processed.
600000 GFF lines processed.
700000 GFF lines processed.
800000 GFF lines processed.
900000 GFF lines processed.
1000000 GFF lines processed.
1100000 GFF lines processed.
1200000 GFF lines processed.
1300000 GFF lines processed.
1400000 GFF lines processed.
1500000 GFF lines processed.
1600000 GFF lines processed.
1700000 GFF lines processed.
1800000 GFF lines processed.
1900000 GFF lines processed.
2000000 GFF lines processed.
2100000 GFF lines processed.
2200000 GFF lines processed.
2300000 GFF lines processed.
2400000 GFF lines processed.
2500000 GFF lines processed.
2600000 GFF lines processed.
2700000 GFF lines processed.
2800000 GFF lines processed.
2900000 GFF lines processed.
2951714 GFF lines processed.
Please Install PySam to use the BAM_Reader Class (http://code.google.com/p/pysam/)Error occured when reading beginning of SAM/BAM file.
  liblzma.so.0: cannot open shared object file: No such file or directory
  [Exception type: ImportError, raised in __init__.py:5]

I've tried installing HTSeq together with PySam in a virtual environment however this doesn't fix the issue. Does anyone have a clue?

Thanks!

**Comment by LegebekeJe** [comment]
The issue was that the system that I'm working on has a newer version of xz-libs.

**Comment by iosonofabio** [comment]
Thanks for reporting
