### ISSUE TITLE
handling output from minimap2

### ISSUE THREAD

**Issue by lucacozzuto** [htseq/htseq#33]
Dear developers, I'm using htseq on the results generated using minimap2 on nanopore reads. 

It looks like I need to turn off the generation of secondary alignment from minimap2 or I get the following error: 

```
Error occured when processing input (record #1 in file data_espress---unclassified_s.bam):
  'NoneType' object has no attribute 'encode'
  [Exception type: AttributeError, raised in _HTSeq.pyx:1379]
```

Not so sure is a htseq problem or minimap2.

**Comment by mantonglaw** [comment]
I create a conda environment for the usage of Htseq. In the virtual environment , I use pip install HTSeq to install the software. I can't find the "_HTSeq.pyx" file, and replace it with the fixed one. I have the same problem when run HTSeq with minimap2 output bam, So could you tell me how to use the fixed one to replace the previous "_HTSeq.pyx" file?

**Comment by iosonofabio** [comment]
Please don't comment on cloud issues. Follow instructions and look up cython on Google
