### ISSUE TITLE
Issue with -h argument

### ISSUE THREAD

**Issue by patchthr33** [htseq/htseq#36]
When trying to use the -h argument I only receive the following information. What do I need to do in order to see the entire list of optional arguments.

`$ htseq-count -h
usage: htseq-count [options] alignment_file gff_file

This script takes one or more alignment files in SAM/BAM format and a feature
file in GFF format and calculates for each feature the number of reads mapping
to it. See http://htseq.readthedocs.io/en/master/count.html for details.

optional arguments:
  -h, --help  show this help message and exit
  --version   Show software version and exit

Written by Simon Anders (sanders@fs.tum.de), European Molecular Biology
Laboratory (EMBL) and Fabio Zanini (fabio.zanini@unsw.edu.au), UNSW Sydney.
(c) 2010-2020. Released under the terms of the GNU General Public License v3.
Part of the 'HTSeq' framework, version 1.99.2.
`

**Comment by iosonofabio** [comment]
Hmm, this is a legit bug with early argument consumption. Let me take a look, you can browse the online docs for now.

**Comment by iosonofabio** [comment]
Fixed on master in cd60265. Will be there in the next release. Thanks for reporting!
