### ISSUE TITLE
htseq-counts multiple BAM header

### ISSUE THREAD

**Issue by Jay-Leung** [htseq/htseq#37]
Hello!

I am opening this issue to clarify the use of htseq-counts for multiple BAM files. I have ran 8 BAM files and the output is a table with no header. Am I correct to say that the column order of the counts follows the order of BAM files I feed into the BAM files argument? 

This parallelization of htseq-counts for multiple files is very helpful, thank you so much! I would suggest to further improve it by adding a header row to specify which sample the counts column came from. 

Once again, thanks!

Regards,
Jay

**Comment by iosonofabio** [comment]
... yes, no header for compatibility with old behavior. But if you choose h5ad or loom as output, you'll have the file names in the right place.

**Comment by iosonofabio** [comment]
@ghar1821: we should add a CLI option `--with-header` that... Well does that 😉

**Comment by iosonofabio** [comment]
@ghar1821: let's add this to the next release as well? It's a pretty minor thing...

**Comment by iosonofabio** [comment]
Added a command-line option in #45, will be there in the next release, closing.
