### ISSUE TITLE
version 0.12.4 fails with multiple cpus

### ISSUE THREAD

**Issue by szzxpxf** [htseq/htseq#4]
Dear developer,

I was trying out the multiple thread feature of version 0.12.4, but it failed with the following error:

 'i' format requires -2147483648 <= number <= 2147483647
   [Exception type: error, raised in connection.py:393]

Nick

**Comment by iosonofabio** [comment]
I fixed a bug about asking for too many CPUs which might be related. You should try the latest github master branch if possible.

Does it work if you process the exact same file with 1 CPU?

Also, please attache the full call to `htseq-count` (I assume that's the script you are using?)

Also, provide some test data (small BAM) and annotations (small GTF) where the error persists so I can test it. If you make those two files and put them onto a shared google drive it'd be great.

Thank you,
Fabio

**Comment by iosonofabio** [comment]
Stale issue, closing. Please request a reopen after you have tried the above.
