### ISSUE TITLE
Confusions about the result

### ISSUE THREAD

**Issue by hfl112** [htseq/htseq#40]
Hi Developers,
I am using the htseq intersection_nonempty mode with --nonunique all to identify exon reads count.
I don't know whether my result is reliable or not, cuz I found a lot of genes only have gene expression at the last exon, and other exons are all zeros? is this normal?

![image](https://user-images.githubusercontent.com/33510929/149568604-6007ea6e-1d1d-464a-b4cf-bbb13cdb9885.png)
Thanks,
hf

**Comment by iosonofabio** [comment]
Depends on the library technology, experiment design, etc. Closing for now, if you have a feeling truth data set please attach <5MB and I'll take a look

**Comment by hfl112** [comment]
Thanks fabio. 
Here I trimmed the top 1000 lines of my htseq result, if possible, can you please give it a look:
[htseq.trimmed.txt](https://github.com/htseq/htseq/files/7873656/htseq.trimmed.txt)
I found those highly expressed exons always the last exon of a given gene.
