### ISSUE TITLE
[BUG] GFF parser doesn't follow GFF spec on quotes, crashes on latest RefSeq GFF3

### ISSUE THREAD

**Issue by davmlaw** [htseq/htseq#41]
**Software versions**

- `HTSeq` 1.99.2 (latest)
- `Python` 3.8
- operating system Ubuntu

**Describe the bug**

HTSeq GFF_Reader throws an exception parsing a line with unbalanced quotes.

[The GFF3 spec  says](https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md)

> Attribute values do not need to be and should not be quoted. The quotes should be included as part of the value by parsers and not stripped.

An alternative implementation - "bcbio-gff" - parses this file without errors (includes the quote in the data)

**Minimal example showing the bug**

HTSeq fails parsing the latest RefSeq GFF annotation:

```
wget https://ftp.ncbi.nlm.nih.gov/refseq/H_sapiens/annotation/annotation_releases/109.20211119/GCF_000001405.39_GRCh38.p13/GCF_000001405.39_GRCh38.p13_genomic.gff.gz
```

Minimal example is the line:

```
NC_000001.11	RefSeqFE	enhancer	6127709	6128003	.	.	.	ID=id-GeneID:112590813;Dbxref=GeneID:112590813;Note=tiled region #11871%3B K562 Activating DNase matched - State 1:Tss;experiment=EXISTENCE:reporter gene assay evidence [ECO:0000049][PMID:27701403];function=activates a minimal TATA promoter and a strong SV40 promoter by Sharpr-MPRA in K562 cells {active_cell/tissue: K562}";gbkey=regulatory;regulatory_class=enhancer
```

```
import HTSeq
gff_containing_quotes = "GCF_000001405.39_GRCh38.p13_genomic.gff.gz" # or minimal example
list(HTSeq.GFF_Reader(gff_containing_quotes))
```

throws exception:

```
    list(HTSeq.GFF_Reader(gff_containing_quotes))
  File "/usr/local/lib/python3.8/dist-packages/HTSeq/features.py", line 146, in __iter__
    (attr, name) = parse_GFF_attribute_string(attributeStr, True)
  File "/usr/local/lib/python3.8/dist-packages/HTSeq/features.py", line 92, in parse_GFF_attribute_string
    quotesafe_split(attrStr.encode())):
  File "src/HTSeq/_HTSeq.pyx", line 2039, in HTSeq._HTSeq.quotesafe_split
  File "src/HTSeq/_HTSeq.pyx", line 2060, in HTSeq._HTSeq.quotesafe_split
ValueError: unmatched quote
```

**Comment by iosonofabio** [comment]
GFF is a little bit of a beast AFAIK, since it changed specs a few times. Since when has the GFF spec changed? Your title just says "latest".

**Comment by davmlaw** [comment]
It fails on the latest RefSeq GFF3 file - the file not the spec

I am not sure if or when the spec changed, I'm quoting from the latest version on the site

**Comment by iosonofabio** [comment]
Alright, thank you. In order to be back compatible, we cannot just break API without a good reason. So it's important to know if and when RefSeq changed their API themselves...

Give me a week or two to revise the paper manuscript and then I'll come back to this and other issues and try to find a way to do the right thing but also be back compatible.

**Comment by davmlaw** [comment]
The bit about GFF3 not having quotes is in the earliest record of their history on that file, in 2016

https://github.com/The-Sequence-Ontology/Specifications/blob/279a07fbc3fb8a9a7cd252b1a20080329a7a8daa/gff3.md

I've used HTSeq to load all the previous GFF3 files on RefSeq's FTP site, I think they just didn't clean their data or something and let a quote go through. The spec allows this, so HTSeq shouldn't crash (especially against an important GFF like this one)

**Comment by iosonofabio** [comment]
Thanks for checking.

The "important file" argument is double edged: if it's so important how could they "not clean the data or something" for many consecutive versions?

I agree it shouldn't crash, the questions is whether those quotes should be:

1. always stripped, what's done now which is consistent with all FTP versions except the latest one,
2. never stripped, which breaks API and won't give the right result for any of their GFF files except the very most recent one
3. try to be smart based on whether the quotes close correctly or not.

Of course, when a dumb computer tries to be too smart things go south. So I'll take a look in 2 weeks, thank you again for reporting.

**Comment by davmlaw** [comment]
I think the GFF parser should follow the GFF spec, and not strip quotes.

Following the spec will not break any previous GFF files, it would only no longer throw an error when there is a quote there. The only time there is a quote there is the latest one.

**Comment by iosonofabio** [comment]
Thanks @davmlaw, I got your opinion. I'm not sure I share all of it, so better safe than sorry. Will keep you posted via this thread.

**Comment by iosonofabio** [comment]
50db456 introduces a new optional argument for the `GFF_Reader` constructor, `gff_version`, which tries to be a little smart about whether it's reading GFF2/GTF or GFF3. The user can enforce this choice if required.

If GFF3 is detected/chosen, quotes are not needed nor stripped, while current behaviour is unchanged for GTF files and GFF2 explicit choice.

This fixed the bug, thanks again for reporting.
