### ISSUE TITLE
how to install Version 2.0.0 and Issues with "Mate records missing" with position-sorted bam

### ISSUE THREAD

**Issue by Xiaofei-git** [htseq/htseq#47]
Dear there,

I got 2 problems with htseq-count.

First, how to install Version 2.0.0?
I see there a new version 2.0.0 released. But, I didn't find there is a source code for it. So, I tried to install it from git at bottom, don't know the version 2.0.0 is not installed. After building, why the "VERSION" was changed to 1.99.2. After installing, it was showed that as below. In fact, this also made my previous htseq (pip install HTSeq) failed to work. When I tried to run:
"............
Finished processing dependencies for HTSeq==1.99.2
"

```
$ htseq-count -h
Traceback (most recent call last):
  File "/home/to/miniconda3/bin/htseq-count", line 4, in <module>
    __import__('pkg_resources').run_script('HTSeq==1.99.2', 'htseq-count')
  File "/home/to/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/to/miniconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1436, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/htseq-count' not found in metadata at '/pbtech_mounts/homes064/to/miniconda3/lib/python3.8/site-packages/HTSeq-1.99.2.dist-info'
````

```
$ git clone https://github.com/htseq/htseq.git
$ cd htseq/
$ more VERSION
2.0.0
$ python setup.py build
$ more VERSION 
1.99.2
$ python setup.py install
```

Second, I got same problem as https://github.com/simon-anders/htseq/issues/37 .  I original thought is to see if version 2.0.0 can fix it, but failed to install it as above. If you need BAM and GTF files to reproduce the issue, please let me know. 
```
$ htseq-count -f bam -r pos -s no --nonunique all --secondary-alignments ignore --supplementary-alignments ignore test_chr12.bam ../hg19.ensGene.gtf > test_chr12_ignore.txt
```

Thanks a lot!

**Comment by iosonofabio** [comment]
Thanks for reporting.

For #1, we are in the process of releasing right now, hopefully online in a day or two.
For #2, as before, try it on a BAM file that is NOT position sorted. If you would like us to debug, please attach a <5MB GTF and a <5MB BAM file that reproduces the issue.

**Comment by iosonofabio** [comment]
Issue 1 is solved, 2.0.0 is released now. Issue 2 is the usual issue that requires input from the user. I'll close for now, if you are indeed able to provide those two files please reopen.

**Comment by Xiaofei-git** [comment]
> Thanks for reporting.
> 
> For #1, we are in the process of releasing right now, hopefully online in a day or two. For #2, as before, try it on a BAM file that is NOT position sorted. If you would like us to debug, please attach a <5MB GTF and a <5MB BAM file that reproduces the issue.

#1, I see it is already 2.0.0 now.
#2, I fixed it. The reason is that there is missing mate for the alignment. For example, for this alignment below, there is only one record for it, the flag of it is 89, one of the SAM decoding is "mate unmapped". So, I used samtools to filter the un-properly paired reads, then the message went away. 

BTW, I like the new version.

Thanks a lot!

```
PC140529:788:C79F5ACXX:5:2113:15015:19938	89	chr12	41757456	3	49M	*	0	CATATTATGGCCAAGGGTCATGATGGCAGGAGTAATCAGAGGTGTTCTT	4GBD@D?:0*1?;HE:<C9HFA?HGIIGHEGFE<F?:FDDHDDDD=@@?	NH:i:2	HI:i:1	AS:i:48	nM:i:0
```

**Comment by iosonofabio** [comment]
Great!
