### ISSUE TITLE
version 0.12.4 aborted when writing output file

### ISSUE THREAD

**Issue by szzxpxf** [htseq/htseq#5]
Dear developer,

I ran into the following error when using htseq-count:
......
......
14969181 alignment pairs processed.
/var/spool/slurm/d/job1321218/slurm_script: line 12: 397186 Killed                  ~/miniconda3/bin/htseq-count -r pos -a 0 -t CDS -s no -i ID -m union -c "$name".tsv $f ~/RNA/cd-hit/nr100/nr100.gff

When I checked the number of lines in the output file, there were only 3.3 million lines while the gff file has 21 million lines. 

I'm not sure if this is an issue with the software itself, or I ran out of memory.

Thank you!

Nick

**Comment by iosonofabio** [comment]
Chances are you ran out of memory. Please repeat with more memory and report.

Thank you

**Comment by szzxpxf** [comment]
Thanks for the reply.
