### ISSUE TITLE
HTSEQ Count file showing 0 reads for a particular gene ( ENSG00000205755 CRLF2, ENSG00000260596 DUX4)

### ISSUE THREAD

**Issue by JAYRJPT** [htseq/htseq#50]
**Software versions**
Specify what versions of the following you are using:
- `HTSeq`- 0.12.4
- `Python` - 2.7.17
- operating system - Ubuntu 18.04.5 LTS
- `STAR` - STAR-2.7.3a
- genome- Hg38
- gtf- gencode.v36.annotation.gtf

Hello Fabio,
I am using HTSEQ to generate the count file of the RNA-Seq data of the B-cell acute lymphoblastic leukemia(B-ALL) patients. While analyzing the output file, I have observed there are 0 reads in the samples which are positive for the CRLF2 translocation( P2RY8::CRLF2, Characterized by high expression of CRLF2). Similarly 0 reads are observed for the DUX4 gene in DUX4 rearranged cases. 
Kindly help in troubleshooting the issue.

Thanks and Regards,
JAY

**Comment by iosonofabio** [comment]
Please try the latest version

**Comment by iosonofabio** [comment]
no answer for a long time, closing.
