### ISSUE TITLE
[BUG]can't import HTSeq

### ISSUE THREAD

**Issue by lizhan96** [htseq/htseq#52]
**Software versions**
Specify what versions of the following you are using:
- `HTSeq`HTSeq                              2.0.1
- `Python`Python 3.9.7
- operating system Linux
- (if applicable) `STAR` or other genome/transcriptome aligner

**Describe the bug**
Can't import HTSeq

**Minimal example showing the bug**

> $htseq-count
Traceback (most recent call last):
  File "/home/lizhan/anaconda3/bin/htseq-count", line 3, in <module>
    import HTSeq.scripts.count
  File "/home/lizhan/anaconda3/lib/python3.9/site-packages/HTSeq/__init__.py", line 13, in <module>
    from HTSeq._HTSeq import *
  File "src/HTSeq/_HTSeq.pyx", line 1, in init HTSeq._HTSeq
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**To Reproduce**
Steps to reproduce the behavior. If this is an `htseq-count` bug report, paste the exact command line you ran on the small example data (see above).

**Comment by iosonofabio** [comment]
Thanks for writing.

How did you install HTSeq? Seems like your installation is broken

**Comment by lizhan96** [comment]
> Thanks for writing.
> 
> How did you install HTSeq? Seems like your installation is broken

I used the following code to install it 
`pip install -i https://pypi.tuna.tsinghua.edu.cn/simple HTseq`

**Comment by iosonofabio** [comment]
That pypi repo is not officially supported, use the official channels or ask the QingHua maintainers of that server to help you.

Closing. Feel free to reopen if you tried official install instructions and get the same error.

**Comment by lizhan96** [comment]
which channels could provided? thanks.

**Comment by iosonofabio** [comment]
Just follow the instructions...
