### ISSUE TITLE
[BUG] yeast_RNASeq_excerpt.sam file

### ISSUE THREAD

**Issue by panyq357** [htseq/htseq#53]
**Software versions**
- `HTSeq`: 2.0.1
- `Python`: 3.10.4
- `samtools`: 1.15.1
- operating system: MacOS 12.4

**Describe the bug**

The `yeast_RNASeq_excerpt.sam` file in [HTSeq_example_data.tgz](http://www-huber.embl.de/users/anders/HTSeq/HTSeq_example_data.tgz) can't be parsed by `HTSeq.SAM_Reader` or `samtools -S`

Both HTSeq and samtools throw the same error.

```
[E::sam_hrecs_error] Malformed key:value pair at line 20: "@PG  ID=Bowtie       VN=0.11.3       CL="bowtie --sam --solexa1.3-quals Scerv yeast_RNASeq_excerpt_sequence.txt yeast_RNASeq_excerpt.sam""
```

After deleting line 20, both software can parse this file correctly.

So, technically this is not a bug, but I think it's better to replace this file to keep newcomers (like me) away from frustrating. 😅

**Comment by iosonofabio** [comment]
That link is dead and if I run:

```bash
$ samtools view example_data/yeast_RNASeq_excerpt.sam | head -n 3
HWI-EAS225:1:10:1284:1974#0/1	0	VIII	394101	255	36M	*	0	0	CTTACGTTTTCTGTATCAATACTCGATTTATCATCT	B9AA>=:=@<;??9@@@@@>?7@@>::??>>==9>>	XA:i:0	MD:Z:36	NM:i:0
HWI-EAS225:1:10:1284:986#0/1	4	*	0	0	*	*	0	0	AATTGGTTTCCCCGCCGAGACCGTACACTACCAGCC	A9(?6.888?8??#######################	XM:i:0
HWI-EAS225:1:10:1284:2012#0/1	0	VII	1001606	255	33M1X2=	*	0	0	TTTGGACTTGATTGTTGACGCTATCAAGGCTGCTGG	25::@@B@>>:3>=6>:8>7:@93?1>8<711.-4?	XA:i:0	MD:Z:36	NM:i:0
```

everything works fine, so I'm closing this for now. If you refer to a different link that is not dead, please reopen.

**Comment by panyq357** [comment]
My apologies. [HTSeq_example_data.tgz](http://www-huber.embl.de/users/anders/HTSeq/HTSeq_example_data.tgz) was copied from this page: https://htseq.readthedocs.io/en/latest/tour.html

So maybe is time to update this doc page :)
