### ISSUE TITLE
Can HTSeq2.0 convert the count generated by htseq-count to tpm?

### ISSUE THREAD

**Issue by Mingjiang-git** [htseq/htseq#55]
Dear HTSeq team, 

Is there any recommended method here? 
Or just follow the normal count to tpm method?
Is there anything that needs special attention?

Thank you！

Best，

Cheng

**Comment by iosonofabio** [comment]
hi @Mingjiang-git,

Thanks for writing. It really depends what you are trying to do.

In any case, that's downstream of HTSeq, closing.

**Comment by Mingjiang-git** [comment]
Dear HTSeq team,

I just want to do differential expression and heat map drawing, so I need comparable data between samples. Can the quantified count from HTSeq2.0 be directly converted using the formula between count and tpm?

Are there any special considerations for calculating gene length here?

Thank you!

Best，
Cheng
