### ISSUE TITLE
HTSeq2.0 count normalization

### ISSUE THREAD

**Issue by Mingjiang-git** [htseq/htseq#56]
Dear HTSeq team,

I just want to do differential expression and heat map drawing, so I need comparable data between samples. Can the quantified count from HTSeq2.0 be directly converted using the formula between count and tpm?

Are there any special considerations for calculating gene length here?

Thank you!

Best，
Cheng

**Comment by iosonofabio** [comment]
Please stop opening new issues on the same question. As I already wrote, this is downstream of HTSeq, it really depends on what exactly you are intending to do. Closing, please do not open another one.
