### ISSUE TITLE
htseq-count could not read custom gff/gtf file

### ISSUE THREAD

**Issue by EthanKhew** [htseq/htseq#57]
Hello 

Hi, I am a beginner in bioinformatics.
I am analyzing a set of RNA-Seq data focusing on small open reading frames (sORF) expression. To look for unannotated ones, I used READemption and ANNOgesic to produce a list of predicted sORF [.gff file = annogesic.bpd286_nutrientbhibrept1_sORF.txt]. Hence, I am having a custom produced .gff and .gtf files. With the same file, I used AGAT to convert my predicted sORF .gff file to .gtf file. I proceeded with STAR mapping and am now at expression count step. Here, I am faced with a few issues:

I used the scripts below to run htseq-count: 
`htseq-count -n 4 -m union -i locus_tag -t sORF -s yes -r name --additional-attr=Name -f bam samtools.sorted_nutrientbhibrept1.rep1Aligned.out.bam bpd286.genomic.ncbi_nutrientbhibrept1_sORF.gff > htseq_samtools.sorted_nutrientbhibrept1.txt`

`htseq-count -n 4 -m union -i gene_id -t sORF -s yes -r name --additional-attr=Name -f bam samtools.sorted_nutrientbhibrept1.rep1Aligned.out.bam bpd286.genomic.ncbi_nutrientbhibrept1_sORF.gtf > htseq_samtools.sorted_nutrientbhibrept1.txt`

Unfortunately, I got back an error for both scripts stating: 
`htseq-count: error: unrecognized arguments: -n bpd286.genomic.ncbi_nutrientbhibrept1_sORF.gtf`
`htseq-count: error: unrecognized arguments: -n bpd286.genomic.ncbi_nutrientbhibrept1_sORF.gff`

Attached below is a google drive link containing all the necessary files used to run my htseq
https://drive.google.com/drive/folders/1-IJNiUpM9CMBzRfIkfpJi9AP0eADJp5g?usp=sharing

I believe the arising issue is probably the format of my .gff/.gtf file but conversion tool (AGAT) has already converted the .gtf files correctly as stated in their documentation. Thus I am lost for the time being and hope you could aid me with my issue. 
The HTSeq framework version that I am using is 0.11.2.

**Comment by iosonofabio** [comment]
Hi @EthanKhew

Thank you for using htseq. Please update your htseq to 2.0.2 and try again. Unfortunately I don't have enough time to debug old versions.

Let me know how it goes!

**Comment by EthanKhew** [comment]
Hi @iosonofabio 

Updating to htseq 2.0.2 has solved all the issue. Thanks so much! I will now close this issue.

**Comment by iosonofabio** [comment]
At your service
