### ISSUE TITLE
ModuleNotFoundError: No module named 'HTSeq._HTSeq'

### ISSUE THREAD

**Issue by slives-lab** [htseq/htseq#58]
I installed using conda, everything appeared to install. However, checking the install failed, and importing HTSeq in python failed. Please advise as I've tried several times without success.

conda create --prefix=~/myprog/htseq_env1 python=3.8.2 numpy pysam pyBigWig matplotlib
pip install HTSeq
python setup.py build install

However, "./test.sh" function failed: ERROR: Failed building wheel for pybigwig. 
I checked install "pip install pyBigWig"
Requirement already satisfied:

python
>>> import HTSeq
ModuleNotFoundError: No module named 'HTSeq._HTSeq'

**Comment by iosonofabio** [comment]
Thanks for reporting. What HTSeq version?

**Comment by slives-lab** [comment]
I also tried: 
python -m .~/myprog/htseq_env/bin/HTseq.scripts.count

which resulted in another error:
~/myprog/htseq_env1/bin/python: Relative module names not supported

**Comment by slives-lab** [comment]
> Thanks for reporting. What HTSeq version?

pip show HTSeq

Name: HTSeq
Version: 2.0.2
Summary: A framework to process and analyze data from high-throughput sequencing (HTS) assays
Home-page: https://github.com/htseq
Author: Simon Anders, Fabio Zanini
Author-email: fabio.zanini@unsw.edu.au
License: GPL3
Location: ~/myprog/htseq
Requires: numpy, pysam
Required-by:

**Comment by iosonofabio** [comment]
Thank you.

Can you please first make the environment with no deps, then activate it, then pip install only HTSeq and see if it imports?

Also, what operating system are you on?

**Comment by slives-lab** [comment]
centos linux is the os. Are you suggesting to create conda environment without any python version?

**Comment by iosonofabio** [comment]
Thank you.

CentOS what version? 

You can specify the python version, but don't install anything at creation time. First create the env, then activate, then pip install HTSeq, then import. Don't install anything else in that environment. That'd help determine if it's HTSeq or a conflict with something else.

**Comment by slives-lab** [comment]
CentOS 7

**Comment by iosonofabio** [comment]
Thank you. Let me know how the test goes!

**Comment by slives-lab** [comment]
conda create --prefix=/myprog/htseq_env_no_dep python=3.8.2
conda activate /myprog/htseq_env_no_dep
pip install HTSeq

  Using cached pysam-0.19.1.tar.gz (3.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.

**Comment by iosonofabio** [comment]
Thanks. That error message is quite terse, not easy to understand what's happening. Can you tell whether it's building HTSeq from source or using the prebuilt wheel?

I'll try on my machine asap and keep you posted.

**Comment by iosonofabio** [comment]
Here's something you could try. After you activate that environment, can you please try to pip install pysam only?

**Comment by slives-lab** [comment]
The install somehow worked today.
conda create --prefix=/myprog/htseq_env_python python=3.8.2
conda activate /myprog/htseq_env_python
pip install HTSeq

>>> import HTSeq #no errors
>>> quit()

However, when I run htseq-count, I encounter another error: Any idea why the gff is throwing an error?

htseq-count -p SAM -c test test.sam rmsk_mm9_repeat_family.gff

Error processing GFF file (line 1 of file rmsk_mm9_repeat_family.gff):
  Failure parsing GFF attribute line
  [Exception type: ValueError, raised in features.py:198]
(/myprog/htseq_env_python) [xxx]$ head rmsk_mm9_repeat_family.gff
chr1    bed2gff L1      3000002 3000156 0       +       .       L1;
chr1    bed2gff L1      3000238 3000733 0       +       .       L1;
chr1    bed2gff Simple_repeat   3000734 3000766 0       +       .       Simple_repeat;
chr1    bed2gff L1      3000767 3000792 0       +       .       L1;

**Comment by iosonofabio** [comment]
Great to hear it installed! I'll close this issue to avoid confusion. Please open a separate one in which:
- you try a GTF file first
- you attach a <5MB GTF file and a <5MB SAM/BAM file that reproduces the error.
Thank you!
