### ISSUE TITLE
Can't install R 4.2 on Ubuntu

### ISSUE THREAD

**Issue by zerolinuxbio** [htseq/htseq#60]
To use the latest version of "DESeq2" package in R, I need to have R version 4.2. I searched a lot and I used multiple methods to install R 4.2 on my system, but all the methods lead me to R 4.1.2.
I also used this website but it did install 4.1.2 ==> https://www.r-bloggers.com/2022/08/installation-of-r-4-2-on-ubuntu-22-04-1-lts-and-tips-for-spatial-packages/

Is there any easy way to install R 4.2?

Thank you in advance for your help.

**Comment by iosonofabio** [comment]
Not the right repo, closing.
