### ISSUE TITLE
htseq-count suggestion - error or warning if BAM and GTF contigs are different

### ISSUE THREAD

**Issue by davmlaw** [htseq/htseq#63]
If you use a GTF file with "chr1" and a BAM with "1", you'll get 0 counts. This seems to crop up in help forums a lot:

https://www.biostars.org/p/294183/
https://www.biostars.org/p/492969/
https://www.reddit.com/r/bioinformatics/comments/143e9g4/htseq_count_is_returning_zero_count_for_all_genes/

The contigs are in the BAM header, perhaps after reading the GTF but before processing the bam you could run a check:

```
if not set(contigs_from_bam) & set(contigs_from_gtf):
    raise ValueError(f"The BAM and GTF file share no contigs, you will get zero counts. Please check they match (eg 'chr1' vs '1")
```

**Comment by iosonofabio** [comment]
Great idea, would you be able to open a PR?
