### ISSUE TITLE
Question about Paired-end Counts for deleted genes

### ISSUE THREAD

**Issue by kevinmyers** [htseq/htseq#66]
**Software versions**
Specify what versions of the following you are using:
- `HTSeq` - version 2.0.3
- `Python` - version 3.10.12
- operating system - CentOS 7
- aligned with `BWA` version 0.7.17-r1188

**Describe the bug**
I am using htseq-count on BAM files from a bacterial species (GCF_003054575.1). We are comparing WT strains as well as two strains with genes knocked out. The knockouts have been verified with whole genome sequencing, but do retain the first 15 and last 18 bp of the ORF. I used paired-end Illumina data to align. When using htseq-count, it records counts for these deleted genes. One gene (RS06365) has counts of ~95 (compared to ~6000 for WT) while the other gene (RS01835) has counts of ~28 (compared to ~160 for WT).

Viewing the alignments with BigWig files (attached are two examples comparing WT and the knockout samples) I see the majority of the gene is missing coverage, but the ends of the genes do have reads that overlap. Previously, when using single-end data, htseq-count did not record any reads for the same deletion strains.

**Command used**
`htseq-count -f bam -s yes <bamfile> <gff>`

**Comments**
I'm curious if this is something commonly observed for paired-end alignments? Clearly these genes are not present in the strains, and so the count results are misleading. We can manually adjust the count data to 0 but I am curious to know why we are seeing these count values for deleted genes. 

**Attachements**
<img width="1367" alt="Example_A" src="https://github.com/htseq/htseq/assets/57917056/74b60a48-f6ea-4d79-94f3-238afd4917f4">
<img width="1367" alt="Example_B" src="https://github.com/htseq/htseq/assets/57917056/eb9e69f3-de1a-4c70-a036-fdda85813069">

**Comment by iosonofabio** [comment]
Thanks for asking. I'm currently traveling so it'll take a few days to fully understand the question. I'll get back to you!

**Comment by kevinmyers** [comment]
Thank you! I appreciate you taking the time to help!

**Comment by iosonofabio** [comment]
Wow, I had forgotten all about this one. This feels like necrobumping and I assume you don't have the issue anymore, but those images show reads partially overlapping with the gene of interest so it seems logical that, depending on the command line options, HTSeq might count them. Perhaps take a look at the `--mode` option and see if that clarifies the situation?

Closing for now, please reopen if this is still a concern.
