### ISSUE TITLE
Error during processing: GFF file checker

### ISSUE THREAD

**Issue by desmodus1984** [htseq/htseq#67]
Hi,

I am trying to count features after WGBS sequencing. I downloaded the gff file from the official NCBI repository,  and I get errors with HTseq-count

`htseq-count V00001.mrkdup.bam /home/juaguila/Bombus/GCF_011952255.1_Bvos_JDL3184-5_v1.1_genomic.gff > V0001.count`
Error processing GFF file (line 12 of file /home/juaguila/Bombus/GCF_011952255.1_Bvos_JDL3184-5_v1.1_genomic.gff):
  Feature exon-XM_033511117.1-1 does not contain a 'gene_id' attribute
  [Exception type: ValueError, raised in features.py:387]

Do you know any way to check/validate the GFF to make sure it will pass and will be good for feature counting?

Thanks;

**Comment by iosonofabio** [comment]
Well, open the GFF in a text editor and check if the attribute `gene_id` is there. If not, choose an attribute that is there. You might want to try using a GTF file instead.
