### ISSUE TITLE
-n parallel CPUs do not speed up

### ISSUE THREAD

**Issue by bounlu** [htseq/htseq#7]
Hi,

I recently switched to python3 version of htseq-count which supports parallel CPUs, hoping that it would speed up the quantification step significantly. I have run tests with `-n 1` and `-n 20`. However, I did not observe any utilization of multiple CPUs or speed up compared to single CPU usage, indeed the two jobs finished in identical time, although the latter 'fakely' seemed to utilize 20 CPUs by increasing the SHR (Shared Memory) rather than %CPU in the `top` command output:

```
time htseq-count -i gene_name -r pos -m intersection-nonempty -s no -n 1 -c test_n1 x.sorted.bam hg19.genes.gtf

real	15m36.056s
user	15m34.173s
sys	0m0.780s

time htseq-count -i gene_name -r pos -m intersection-nonempty -s no -n 20 -c test_n20 x.sorted.bam hg19.genes.gtf

real	15m36.121s
user	15m32.738s
sys	0m3.773s
```

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/17899927/81593244-c0d7f000-93f1-11ea-9355-8ec117ba922f.png">

I am wondering if I am right to expect speed up by increasing this parameter and how it was implemented. Any bench-marking done by others possibly?

@iosonofabio @simon-anders
Thanks for the great tool and help.

**Comment by hennion** [comment]
I have the same problem, I tried to increase `n` (in version 0.12.3) but I don't see any speed up. I run : 
htseq-count -r pos -f bam -i gene_id -s reverse -c {output.count} -n 30 {input.sort} {input.annotation}
This step is really limiting for me (it takes ~10h to process a human RNAseq sample), so any solution to make it run faster would be highly appreciated!! 
Thank you very much!

**Comment by iosonofabio** [comment]
Do you actually have 30 CPUs on that machine?

**Comment by iosonofabio** [comment]
In any case, let me try and debug a little. This days are a little hectic so any help would be appreciated

**Comment by hennion** [comment]
Yes, I run it on a cluster with enough cores, via snakemake. As for bounlu, the CPU are allocated but only one is really used. 
![htop](https://user-images.githubusercontent.com/19472666/83606945-b2a56b80-a57a-11ea-926c-4173930b8b28.png)
I'll be happy to help if I can, please let me know which tests could be useful. 
Thanks!

**Comment by iosonofabio** [comment]
Let me understand: how many BAM files are you processing?

**Comment by hennion** [comment]
Only one here.

**Comment by iosonofabio** [comment]
That's it. The -n can process up to n BAM files in parallel to speed up, but cannot use multiple cores on the same file.

I'll change the docs to be more accurate.

Your options are splitting the bam file into several or waiting. If you could make a PR that extends the multicore design to a single file that'd be great, but I warn you it might be quite challenging.

**Comment by hennion** [comment]
OK, thank you, I misunderstood it. I'll think about it and let you know if I can help to solve that. 
BW

**Comment by bounlu** [comment]
Ahh I see, now it's clear why. Then I have 2 suggestions:

1. If 1 bam file is given, -n option should be disabled, as it is useless but keeps the cores busy.
2. We just need this (obviously easier to say rather than implementing):
http://bioinf.wehi.edu.au/featureCounts/
`featureCounts -T 10`
`htseq-count -T 10`

**Comment by iosonofabio** [comment]
I implemented option 1 in the latest master branch.

As of 2, yes there is that, subread, STAR, etc etc. Feel free to use another software if you like it better. Or to start a PR, of course ;-)
