### ISSUE TITLE
htseq-count-barcodes for single-cell bams from CellRanger

### ISSUE THREAD

**Issue by aoulas** [htseq/htseq#78]
I would like to use “htseq-count-barcodes” script, in order to analyse single-cell barcode/UMI .bam files generated via CellRanger. 
I am having trouble generateing the .gff file required to run the script. Can you please provide a template .gff file specifically for the running htseq-count-barcodes.

Many thanks,

Anastasis

**Comment by iosonofabio** [comment]
Please include the things mentioned in the email...

**Comment by iosonofabio** [comment]
Do you have a gtf instead?

**Comment by aoulas** [comment]
Unfortunately no, that is what I need help with....

Best,

A.

**Comment by iosonofabio** [comment]
Can you convert the gtf into q gtf first? Gtf is better tested, helping you would be faster

**Comment by iosonofabio** [comment]
Gff into gtf

**Comment by iosonofabio** [comment]
Closing for user inactivity. Please attach the GTF file and the exact command line one needs to call to reproduce and reopen this issue if you still need this, so I can help :-)

Unfortunately, I cannot provide direct help converting GFF into GTF as my schedule is a little busy for that kind of basic support.
