### ISSUE TITLE
htseq-count and htseq-count-barcodes do not produce the similar results for annotations

### ISSUE THREAD

**Issue by sinanugur** [htseq/htseq#79]
Hi,

I am using **htseq-count** and **htseq-count-barcodes** on a 10x cellranger output bam file.

However, I noticed that a genomic feature in the GFF file expressed around 500 but when I inspect the results on the barcode level, there was almost no expression. 

In other words, I expect to see that 500 reads distributed among the cells. 

I run like this:

```
htseq-count -f bam possorted_genome_bam.bam hsa.mir.gff -t pre_miRNA -i ID

htseq-count-barcodes -f bam possorted_genome_bam.bam hsa.mir.gff -t pre_miRNA -i ID
```

What might be the reason? Does htseq-count-barcodes also deal with cellranger UMIs so that it removes duplicates automatically?

Cheers,
@sinanugur

**Comment by iosonofabio** [comment]
Thanks for reporting. Can you please attach a small example (BAM < 5MB, GTF < 5MB)?

Hard to help without one.

**Comment by iosonofabio** [comment]
Closing for user inactivity, please reopen if you can attach a small example so I can help you :-)
