### ISSUE TITLE
Error extracting bam-alignments from fasta-input

### ISSUE THREAD

**Issue by brobr** [htseq/htseq#8]
Hi,
Thanks for the program and the ability to use HTSeq from within a python pipeline as exemplified in "https://htseq.readthedocs.io/en/master/counting.html#counting-ungapped-single-end-reads". 
In such a context, during counting of alignments it has been set up that alignments of a particular length ('XtoY') are extracted to another bam-file via
>bam_writerXtoY = HTSeq.BAM_Writer.from_BAM_Reader("<path_to>}_XtoY.bam", bam_reader)

With bam files generated by the STAR aligner from fastq input -thus including quality parameters - there is no problem extracting alignments this way and sort them to a separate file. When the bam file is an alignment of fasta sequences (thus without any sequence-quality info), it raises this error: 
>  
>--> 169            bam_writerXtoY.write( almnt )
>
>/usr/lib64/python3.8/site-packages/HTSeq/__init__.py in write(self, alnmt)
    937 
    938     def write(self, alnmt):
--> 939         self.sf.write(alnmt.to_pysam_AlignedSegment(self.sf))
    940 
    941     def close(self):
>
>python3/src/HTSeq/_HTSeq.pyx in HTSeq._HTSeq.SAM_Alignment.to_pysam_AlignedSegment()
>
>python3/src/HTSeq/_HTSeq.pyx in HTSeq._HTSeq.SequenceWithQualities.qual.__get__()
>
>python3/src/HTSeq/_HTSeq.pyx in HTSeq._HTSeq.SequenceWithQualities._fill_qual_arr()
>
>ValueError: Quality string has not the same length as sequence.

Could the class function be adapted so that it would be possible to pass on a flag in `write(almnt)` that enables alignments to be extracted that do not have quality-scores?

PS1: `samtools view` output of the bamfile that causes the error;
>1661076_4	16	12	20572	1	12M	*	0	0	CTTCGCCGGGGT	*	NH:i:3	HI:i:1	AS:i:11	nM:i:0
1151992_2	0	12	20573	3	13M	*	0	0	TTCGCCGGGGTGG	*	NH:i:2	HI:i:1	AS:i:12	nM:i:0

PS  Possibly, a similar reason (fasta-based alignment as input) could have led to the problem reported here: https://www.biostars.org/p/342814/

**Comment by iosonofabio** [comment]
Most certainly. My bandwidth is currently limited though, would you start a PR on this?

Thank you

**Comment by brobr** [comment]
Sorry, I am a newb with respect to github and would not know how to accomplish this easily (or without mucking stuff up). Also, I do not see immediately where/how this could be accomplished in the code. 

Initially, I wondered -because the starting bam file would not have this quality string either-  whether this flag could be passed in via the creation of the bam_reader from which the bam-writer is constructed (based on a guess that `check_sq` was for checking sequence quality:
>class BAM_Reader(object):
>
>    def __init__(self, filename, check_sq=True):
)

But the writer only takes over the sam-header from the reader, thus the addition of `False` to the call `bam_reader = HTSeq.BAM_Reader(<path-to-bamfile>,False)` had not an effect on the subsequent `HTSeq.BAM_Writer.from_BAM_Reader` and the `Value error` above. 

Then, when checking where the Error is raised, due to my minimal python expertise, I got lost in the code. So, overall, I am not sure whether this would be a good approach in the first place.

My excuses I cannot be more of a help at this moment.

**Comment by iosonofabio** [comment]
Thanks for looking. I'm swamped writing a few papers ATM but will leave this open for a while and maybe someone will help out.

**Comment by brobr** [comment]
Good luck with the papers. 

I made some 'progress'
1.  `check_sq`  tells whether the header has SQ entries (from pysam.AlignmentFile code), so not relevant for this issue.
2. By  commenting out the blocks with `seq_len != len(self._qualstr)`  and then redirecting the `noquals` to the production of a fake `1` quality line in _HTSEQ class 
 equenceWithQualities()  (see attached patch)  leads to output like:

>911593_2        16      1       6400    255     15M     *       0       0       CGCTGCTCTACGAGA """"""""""""""" NH:i:1  HI:i:1  AS:i:12 nM:i:1  MD:Z:0A14
1015136_2       16      1       6403    0       13M     *       0       0       AGCTCTACGAGAC   """""""""""""   NH:i:9  HI:i:1  AS:i:10 nM:i:1  MD:Z:0T12


Obviously, this hack is not generally useful; it would be better if a not-processable quality string (i.e. the `"*"` after the read-sequence in the original/input bam-file) is simply propagated to the line that will be written to the new file (i.e. 'crap in, same crap out'). But that is easier said than done. Via `"noquals"` these alignments are treated the same as those with valid quality scores and this makes them  incompatible. Ideally, they would be piped along as just a Sequence (without quality), but I did not see how to implement this in a straightforward manner.   
[writefromfastabam_hack](https://github.com/htseq/htseq/files/4690299/writefromfastabam_patch.txt)

**Comment by iosonofabio** [comment]
I'd be happy to take a stab at this, but for that I need at least a concrete example of a BAM file without qualities (coming from Fasta, as you phrased it). Please provide that example and I'll take a look, otherwise I'm afraid it remains too vague for implementing and I'll have to close this.

**Comment by iosonofabio** [comment]
Hmm, this one's open for almost a year without a response from the user. Closing. Please reopen if you have a minimal example I can use for testing.

Meanwhile FYI, quite a few bugs with no-quality, corrupted, or zero-length sequences from Pacbio and ON have been fixed in htseq, so you might also just give it a go on the original file and the issue might have been solved via other committs.
