### ISSUE TITLE
Using htseq-count-barcodes without read return[BUG]

### ISSUE THREAD

**Issue by CharleyWang** [htseq/htseq#82]
**Software versions**
Specify what versions of the following you are using:
- `HTSeq`: 2.0.5 and 2.0.1
- `Python`: 3.9 and 3.7
- operating system: Linux
- (if applicable) `STAR` or other genome/transcriptome aligner
Cell ranger
**Describe the bug**
Trying to get counts (10X mapping bam file) for each input feature in a GTF file using  htseq-count-barcodes. Only get transcript feature as a single column like 

"exon_PF3D7_0100100.1-E1"
"exon_PF3D7_0100100.1-E2"
"exon_PF3D7_0100200.1-E1"
"exon_PF3D7_0100200.1-E2"
"exon_PF3D7_0100300.1-E1"
"exon_PF3D7_0100300.1-E2"
"exon_PF3D7_0100400.1-E1"
............
"utr_PF3D7_1478600.1_2"
"utr_PF3D7_1478800.1_1"
"utr_PF3D7_1478800.1_2"
"utr_PF3D7_1479000.1_1"
"utr_PF3D7_1479000.1_2"
__no_feature
__ambiguous
__too_low_aQual
__not_aligned
__alignment_not_unique

The results does not include any read counts. Can get count for the command htseq-count. 
 
"utr_PF3D7_1478100.1_1" 0
"utr_PF3D7_1478100.1_2" 0
"utr_PF3D7_1478600.1_1" 1
"utr_PF3D7_1478600.1_2" 0
"utr_PF3D7_1478800.1_1" 0
"utr_PF3D7_1478800.1_2" 6
"utr_PF3D7_1479000.1_1" 0
"utr_PF3D7_1479000.1_2" 0
__no_feature    654
__ambiguous     4918
__too_low_aQual 0
__not_aligned   0
__alignment_not_unique  0

I also include couple of lines from the SAM file used here.

ACGTACTATCAAATTCTTACAATATATTATACCTAATTTCCTAATATTATAATGAATACTTTTAGAGGTATATATATCAAACAGACATATGATGAATTTCTCGTCTTTTTCTATTTCATATAAAATCTTTTCTGATTCCTTTCTTTTATCATGGTCATTAGACCAGGTATCATATAAAGCGTCGATTATTATTTTATATTTTTCTTCAATTTCTTCCATACGCAAAATAAAATCAAAATAT      *       CB:Z:GTCGTGCGAAACGTGG   XA:Z:XM-CB      XM:Z:TTCGAATTTCTC       ic:i:3  im:Z:m84039_230421_212846_s1/63836586/ccs/4630_4912,m84039_230421_212846_s1/57414612/ccs/7572_7854,m84039_230421_212846_s1/175313742/ccs/9751_10033     is:i:3  it:Z:TTCGAATTTCTCGTCGTGCGAAACGTGG,TTCGAATTTCTCGTCGTGCGAAACGTGG,TTCGAATTTCTCGTCGTGCGAAACGTGG     rc:i:1  RG:Z:e4927d21   zm:i:19279678   mg:f:100        NM:i:0
molecule/21227937       16      Pf3D7_14_v3     1274408 60      275=    *       0       275     GTATTGTCACTATAATGAAATCCATCTCTATTATTCCAATAACGTACTATCAAATTCTTACAATATATTATACCTAATTTCCTAATATTATAATGAATACTTTTAGAGGTATATATATCAAACAGACATATGATGAATTTCTCGTCTTTTTCTATTTCATATAAAATCTTTTCTGATTCCTTTCTTTTATCATGGTCATTAGACCAGGTATCATATAAAGCGTCGATTATTATTTTATATTTTTCTTCAATTTCTTCCATACGCAAAATAAAATC     *       CB:Z:TAGGATCTGCTAAGGG   XA:Z:XM-CB      XM:Z:ACATATCGGGCA       ic:i:1  im:Z:m84039_230421_212846_s1/26281333/ccs/7943_8218     is:i:1  it:Z:ACATATCGGGCATAGGATCTGCTAAGGG       rc:i:1  RG:Z:e4927d21   zm:i:21227937   mg:f:100        NM:i:0
molecule/10951757       16      Pf3D7_14_v3     1274410 60      2S222=1S        *       0       222     GCATTGTCACTATAATGAAATCCATCTCTATTATTCCAATAACGTACTATCAAATTCTTACAATATATTATACCTAATTTCCTAATATTATAATGAATACTTTTAGAGGTATATATATCAAACAGACATATGATGAATTTCTCGTCTTTTTCTATTTCATATAAAATCTTTTCTGATTCCTTTCTTTTATCATGGTCATTAGACCAGGTATCATATAAAGCGTCC       *       CB:Z:CGCTGCAGACGAGAGT   XA:Z:XM-CB      XM:Z:CACAGTTACGTG       ic:i:1  im:Z:m84039_230421_212846_s1/246616174/ccs/10907_11132  is:i:1  it:Z:CACAGTTACGTGCGCTGCAGACGAGAGT       rc:i:1  RG:Z:e4927d21   zm:i:10951757   mg:f:100        NM:i:0

The GTF file used here.
18 Pf3D7_01_v3     VEuPathDB       transcript      313824  319525  .       +       .       gene_id "exon_PF3D7_0107600.1-E1"; transcri      pt_id "exon_PF3D7_0107600.1-E1"; gene_name "exon_PF3D7_0107600.1-E1"; transcript_name "exon_PF3D7_0107600.1-E1"; biotype "singleExo      n";
   19 Pf3D7_01_v3     VEuPathDB       exon    313824  319525  .       +       .       gene_id "exon_PF3D7_0107600.1-E1"; transcript_id "e      xon_PF3D7_0107600.1-E1"; gene_name "exon_PF3D7_0107600.1-E1"; transcript_name "exon_PF3D7_0107600.1-E1"; biotype "singleExon";
   20 Pf3D7_01_v3     VEuPathDB       transcript      313824  314617  .       +       .       gene_id "utr_PF3D7_0107600.1_1"; transcript      _id "utr_PF3D7_0107600.1_1"; gene_name "utr_PF3D7_0107600.1_1"; transcript_name "utr_PF3D7_0107600.1_1"; biotype "singleExon";
   21 Pf3D7_01_v3     VEuPathDB       exon    313824  314617  .       +       .       gene_id "utr_PF3D7_0107600.1_1"; transcript_id "utr      _PF3D7_0107600.1_1"; gene_name "utr_PF3D7_0107600.1_1"; transcript_name "utr_PF3D7_0107600.1_1"; biotype "singleExon";

**Comment by CharleyWang** [comment]
Make a screenshot of Sam file here

![image](https://github.com/htseq/htseq/assets/6835970/9bf50ed1-f1b0-4750-9839-a0b0f674d101)

**Comment by CharleyWang** [comment]
The screenshot of running the command

![image](https://github.com/htseq/htseq/assets/6835970/1e6ee70f-5b05-41c6-b6b8-277d714e32d7)

**Comment by iosonofabio** [comment]
Thank you.

Could you please attach the GTF file (small example), the SAM/BAM file (small example), and the command you're trying to run (same small example)?

Cheers, 
Fabio

**Comment by CharleyWang** [comment]
[Archive.zip](https://github.com/htseq/htseq/files/15140702/Archive.zip)
Thanks! Attached here

**Comment by CharleyWang** [comment]
Here is the command.
htseq-count-barcodes  -c aaa.csv  o.sam PlasmoDB-62_Pfalciparum3D7.onlyExon.gtf.sorted

**Comment by iosonofabio** [comment]
Hey,

these reads look a little odd. 10X says they use the `UB` BAM tag to signify the (corrected) molecular barcode, however this tag is missing here (hence no molecules are identified). The reads do appear to include a tag called `XM` that looks reminescent of a molecular barcode, so you can set that using the `--UMI XM` option of `htseq-count-barcodes` and you'll get a (big) table. No idea if that includes all barcodes, only good ones, and what else.

Does that help?

**Comment by CharleyWang** [comment]
Hello. Thank you for your prompt reply. I'm new to single-cell analysis. We've observed that the barcode length should be 16 base pairs in our case, and it appears that the CB tag should represent the barcode. Please correct me if I'm mistaken. Thanks once again.

**Comment by iosonofabio** [comment]
Then it's likely there's a big upstream or that the fix above is what you need. Maybe read up a bit about UMIs as they are an important piece of the technology and you seem to be confusing them with cell barcodes.

**Comment by CharleyWang** [comment]
Thank you. Initially, I believed the issue might be related to barcodes, but I've now realized it's actually the lack of clarification on the UMI tag. Additionally, I want to clarify that the BAM format I provided is specific to PacBio data. Thanks once again for your assistance!
