### ISSUE TITLE
  Exception type: ValueError, raised in __init__.py:712

### ISSUE THREAD

**Issue by Eulogy320** [htseq/htseq#9]
hello masters! I have a problem running a section of my bash script where htseq-count is the star.  
```
cd $map_nor
for dir in $map_nor/* ; do
        dir=${dir}
        echo " Haciendo conteos de ${dir##*/}"
        htseq-count -o ${dir}/samout -i gene_id -s no -m intersection-strict --max-reads-in-buffer 100000000 --secondary-alignments ignore --supplementary-alignments ignore ${dir}/accepted_hits_ordenadas.sam $index > ${dir}/${dir##*/}.count 2> ${dir}/${dir##*/}.err &
done
```
and the error message is : 
```
Error occured when processing SAM input (line 65455163 of file /home/mgonzalez/Omega/trim_normales/mapeo/SRX1479335/accepted_hits_ordenadas.sam):
  'pair_alignments' needs a sequence of paired-end alignments
  [Exception type: ValueError, raised in __init__.py:712]
```
I try with and without  [ ... ] 
```
--max-reads-in-buffer 100000000 --secondary-alignments ignore --supplementary-alignments ignore  
```
and the error still appears. 

The " funny" things is i have seven paired-end sequences in my analysis and the bams orders files of SRX1715773 SRX1715774 SRX1715775 works fine!, but the SRX1479335 SRX1479336 SRX1479343 SRX1479344 send me the previus error.  Then i did :

`awk 'NR==65455163' accepted_hits_ordenadas.sam`

and the output was : 

`SRX1479335.41748068	16	MT	2741	50	63M	*	0	0	ATTTATTAATGCAAACAGTACCTAACAAACCCACAGGTCCTAAACTACCAAACCTGCATTAAA	FFFFFFFFFFFFFFFFIIFFIIIIIIIFBIIFFIIIIFIIIIIIIFFIIIIIIIIIIIIIIII	AS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:63	YT:Z:UU	XS:A:+	NH:i:1`

So the question is , How i fix this error? where is mi error ? sequence problem? mapping problem? setting htseq-count command line problem? 

In fact,  [here](https://github.com/simon-anders/htseq/issues/37) same issue is reported. 
By the way Thanks a lot for the tools , RNA gods bless you!

**Comment by iosonofabio** [comment]
Try unsorted BAM files first.

**Comment by iosonofabio** [comment]
This seems to be stale. Please reopen after you have tried the above.
