### ISSUE TITLE
HTSeq-count is not accepting inputs standard input  (-)

### ISSUE THREAD

**Issue by TNalpat** [htseq/htseq#93]
Hello,
We are using htseq-count 2.0.9 and pthon/3.12.4. We were trying count feature by each chromosome. We tried, 

samtools view bam-file  chr  |  htseq-count -s reverse -m intersection-nonempty -f sam -r pos - gtf-file 

and we get following error message:

Error occurred when reading beginning of SAM/BAM file.
  file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False
  [Exception type: ValueError, raised in libcalignmentfile.pyx:1000]

It is working perfectly with older version of HTSeq.

Thanks
Thomas

**Comment by iosonofabio** [comment]
Thank you for reporting. What's the last version that works?

**Comment by TNalpat** [comment]
Thanks for quick response. We were actually using quite old version v.0.6.1p2.

**Comment by iosonofabio** [comment]
Thanks. What's the last version that works?

**Comment by TNalpat** [comment]
We figured out the issue. It needed sam header to run it correctly.  Following command seems to be working:
amtools view  -h bam-file chr | htseq-count -s reverse -m intersection-nonempty -f sam -r pos - gtf-file

Thanks for your help!

**Comment by iosonofabio** [comment]
Thanks!
