### ISSUE TITLE
Understanding Special Counters

### ISSUE THREAD

**Issue by MartaBenegas** [htseq/htseq#96]
Hi HTSeq team, 

I have some issues understanding how the "[special counters](https://htseq.readthedocs.io/en/release_0.11.1/count.html#usage)" are computed. From what I understand from [this comment](https://github.com/simon-anders/htseq/issues/95#issuecomment-612701977), those numbers refer to alignments (or BAM entries/records) rather than to actual reads, right? 

Thus, I would expect the "__total_records" to correspond to the total number of alignments in the BAM file, but it is not the case for my example data:

```
$ tail counts_output.tsv 
ENSMUSG00000128351	0
ENSMUSG00001074846	0
ENSMUSG00002076083	0
__no_feature	223249
__ambiguous	55148
__too_low_aQual	0
__not_aligned	0
__alignment_not_unique	499500
__feature	1270797
__total_records	2048694
$ samtools view -c SRR937558.bam 
2073514
```

What do the "__total_records" and "__feature" stand for? It is not explained in the manual. How are the other metrics computed?

Here you have a [drive link](https://drive.google.com/file/d/1OjfymxcVs0BZZ2H0g97ki073oRTWAjvZ/view?usp=sharing) to download my bam file. I used the  [Ensembl Mouse gff3](https://ftp.ensembl.org/pub/release-113/gff3/mus_musculus/Mus_musculus.GRCm39.113.gff3.gz) for counting. HTSeq command:
```
htseq-count -n 10 -r name -s no -a 10 -t gene -i gene_id -m union -c /data/output/counts_output.tsv --secondary-alignments score --supplementary-alignments score /data/input/SRR937558.bam /data/input/Mus_musculus.GRCm39.113.gff3
```

Thanks in advance,
Marta.

**Comment by iosonofabio** [comment]
Hi @MartaBenegas ,

The total number depends on a few things I believe, especially if you are using paired end mode. `__feature` should refer to the number of (pairs of) alignments within a feature. We should do a better job at documenting this, I agree. Do you think you'd have time to open a PR?

As for the test data, please create a small example with a GTF and a BAM each smaller than 5 MB. Thanks!

**Comment by MartaBenegas** [comment]
Hi @iosonofabio , thanks for the prompt response!

I'd gladly help but I still do not understand the values completely. 

How do you obtain those statistics? Do you use samtools or custom code? On which things depend the total number of counts then?

Here you have a smaller version of the data with only chromosome 16 (remove the .txt at the end of the file names):
[chrom16.bam.txt](https://github.com/user-attachments/files/17829697/chrom16.bam.txt)
[Mus_musculus.GRCm39.113.chromosome.16.gff3.gz.txt](https://github.com/user-attachments/files/17829698/Mus_musculus.GRCm39.113.chromosome.16.gff3.gz.txt)

**Comment by gl-eb** [comment]
Both your full-size and smaller BAM files are sorted by position while you are running htseq-count with the `-r name` option. Running either `samtools sort -n` beforehand or htseq-count with the `-r pos` option resolves the mismatch between total counts from htseq-count and the output of `samtools view -c`.

The only difference is that htseq-count reports the number of read pairs while samtools counts actual reads. Thus the sum of all feature counts as well as the special counters from htseq-count is 1,036,757 while samtools outputs the exact double of that number: 2,073,514.

By the way, which version of HTSeq are you using? I have not seen the `__feature` and `__total_records` special counters in htseq-count output before.

**Comment by MartaBenegas** [comment]
Hi @gl-eb ,

Thank you, I understand the difference between samtools and HTSeq outputs now. 

I was using an old colleague's script to run HTSeq and I just realized that the "__feature" and "__total_records" are statistics added by him. I extracted the command from the execution but I didn't realize the post-processing, I'm really sorry for the confusion!  The "__feature" is the count sum of all features and the "__total_records" is the sum of that and the special counters. 

I have another question now that I would like to confirm with you. I have the total number of uniquely mapped reads from STAR output, but this doesn't match the count sum of all features. Is this because of the `--secondary-alignments score --supplementary-alignments score` parameters? Otherwise, if only uniquely mapped reads were used during quantification, I would expect those numbers to match. 

Thank you again for your prompt response and sorry for the misunderstanding with the special counters.

**Comment by iosonofabio** [comment]
OMG guys postprocessing - that's funny!

Happy to see it's clear now and many thanks to @gl-eb for providing the answer. Closing 🦄

**Comment by gl-eb** [comment]
> I have another question now that I would like to confirm with you. I have the total number of uniquely mapped reads from STAR output, but this doesn't match the count sum of all features. Is this because of the `--secondary-alignments score --supplementary-alignments score` parameters? Otherwise, if only uniquely mapped reads were used during quantification, I would expect those numbers to match.

@MartaBenegas I would guess that this is indeed the reason. You can easily test this by running htseq-count again with the `--secondary-alignments=ignore --supplementary-alignments=ignore` options.
