### ISSUE TITLE
Should I be concerned in paired-end forward stranded libraries about Warning: Mate records missing for 835 records?

### ISSUE THREAD

**Issue by denvercal1234GitHub** [htseq/htseq#99]
Hi there, 

Thank you for the tools (v.2.0.2)

In the older repo, it seemed to have been fixed, but in my `htseq-count` output for paired-end stranded forward libraries ran today as below, there are a number of `Warning: Mate records missing for 835 records; first such record: <SAM_Alignment object: Paired-end read 'LH00235:277:22MYFFLT3:3:2151:35340:17022' aligned to chr1:[23695840,23696418)/+>.` as an example. 

Would you mind helping me understand the implications of this warning in DEGseq diff gene analysis downstream?

Thank you for your help!

```
############# Index ref genome 
STAR --runThreadN 24 --runMode genomeGenerate --genomeDir "$GENOME_DIR" --genomeFastaFiles GRCh38.primary_assembly.genome.fa --sjdbGTFfile gencode.v47.annotation.gtf --sjdbOverhang 149
```

```
 STAR --genomeDir "$GENOME_DIR" \
       --runThreadN "$THREADS" \
       --readFilesCommand zcat \
       --readFilesIn "$r1_file" "$r2_file" \
       --outFilterMultimapNmax 1 \
       --alignSJoverhangMin 5 \
       --outSAMtype BAM SortedByCoordinate \
       --outSAMattributes NH HI AS nM XS \
       --outFilterScoreMinOverLread 0.66 \
       --outFilterMatchNminOverLread 0.66 \
       --quantMode TranscriptomeSAM \
       --outSAMstrandField intronMotif \
       --outFileNamePrefix "$sample_output/" \
       > "$sample_output/star_align.log" 2>&1
```

```
# Index the BAM file
  samtools index "$bam_file"

# Run HTSeq-count for stranded forward library
  htseq-count --format=bam \
              --stranded=yes \
              --order=pos \
              --minaqual=10 \
              --type=exon \
              --idattr=gene_id \
              --mode=intersection-nonempty \
              "$bam_file" "$GTF_FILE" > "$htseq_output"
```

**Comment by iosonofabio** [comment]
Well, htseq is telling you that you have unpaired alignments, e.g. one reads aligns but the mate doesn't.

Whether that is a problem depends on what you expect: how many alignments are just fine? The implications on DE are as you would imagine, highly dependent on what fraction of reads ends up unpaired.

Not sure what you mean by "In the older repo, it seemed to have been fixed".
